import type { Metadata } from "next";
import "../globals.css";
import { ConvexClientProvider } from "@/providers/convex_client_provider";
import OrgList from "./__components/Sidebar/OrgList";
import Featured from "./__components/Sidebar/Featured";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode;}>) {
  return (
    
    <html lang="en">
      <body className="min-h-screen bg-black w-full flex">
      <ConvexClientProvider>
        <OrgList />
        <Featured />
        {children}
      </ConvexClientProvider>
      </body>
    </html>
  );
}
